import Head from "next/head";
import Header from "../components/Header/Header";
import Banner from "./../components/Banner/Banner";

export default function Home() {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Medium 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header starts*/}
      <Header />
      {/* main starts here */}
      <main>
        <Banner />
      </main>
    </div>
  );
}
